# 统计信息页面颜色配置

# 字体颜色 (默认白色 FFFFFF)
font_color=E8F5EE
# 边框大小 (默认 0.8)
border_size=1.1
# 边框颜色 (默认深灰色 262626)
border_color=2A3A32
# 文字透明度 (默认 11，范围 0-255)
alpha=200

# 图表边框颜色 (默认蓝色 0000FF)
plot_bg_border_color=0000FF
# 图表背景色 (默认深灰色 262626)
plot_bg_color=2A3A32
# 图表中线条数据的颜色 (默认白色 FFFFFF)
plot_color=FFFFFF
# 指定字体，例如 "SimHei" 或者留空 '' 以跟随 mpv.conf 中的 osd-font
font='Maple Mono Normal NF CN Regular'
# 字体大小 (默认 8)
font_size=22